### ISSUE TITLE
Define the continentOcean list

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#1]
What values are these

**Comment by chrispmeyer** [comment]
John - this should be the same field as Biocode schema: "ContinentOcean"
Should it be a controlled pick list:
Pacific Ocean
Atlantic Ocean
Arctic Ocean
Southern Ocean
Indian Ocean
Red Sea
Mediterranean Sea
etc.
North America
South America
Europe
Asia
Australia
Africa
Antarctica
etc.

**Comment by jdeck88** [comment]
Here is a list of oceans and seas:

http://www.infoplease.com/ipa/A0001773.html

What about large lakes, e.g. Caspian Sea, Lake Baikal, Lake Tahoe, etc...?

Where do we draw the line?

John

**Comment by chrispmeyer** [comment]
I'd stick with that list and not do large lakes, etc. - they's be considered parts of continents, whereas the Oceans & Seas are extralimital

**Comment by jdeck88** [comment]
OK, here is the complete list to use:

Africa
Andaman Sea
Antarctica
Arctic Ocean
Asia
Atlantic Ocean
Australia
Baltic Sea
Bering Sea
Caribbean Sea
East China Sea
Europe
Gulf of Mexico
Hudson Bay
Indian Ocean
Japan Sea
Mediterranean Sea
North America
North Sea
Okhotsk Sea
Pacific Ocean
Red Sea
South America
South China Sea
Southern Ocean
