### ISSUE TITLE
Error when trying to re-upload project

### ISSUE THREAD

**Issue by lplaisance** [biocodellc/arms-fims#10]
I have tried to re-upload the PIRE metadata project, while it passes validation it returns a "Server Error" with no additional information when I try to upload it.
The metadata file is attached to this message.
[PIRE-ARMS-Metadata-p.xlsx](https://github.com/biocodellc/arms-fims/files/366393/PIRE-ARMS-Metadata-p.xlsx)

**Comment by jdeck88** [comment]
Here is the error message from the logs (there are some other messages that show up when NOT trying to upload).  This message i think is the one causing the server error.  

org.springframework.orm.jpa.JpaSystemException: Null value was assigned to a property of primitive type setter of biocode.fims.arms.entities.Deployment.numLayers; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of biocode.fims.arms.entities.Deployment.numLayers

**Comment by jdeck88** [comment]
This is fixed now with recent commit
