### ISSUE TITLE
Save spreadsheets to a permanent directory

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#11]
Spreadsheets, when loaded, are currently saved in jetty/temp (the base directory of deployment) and named using some type of hash.  I want to change this for ARMS to:

1) save spreadsheets to a permanent directory specified in configuration file: e.g. /opt/arms_spreadsheets

2) Keep using hashed name but save the hashed name in the expeditions table as we do for NMNH (NMNH has this same spreadsheet saving function).

3) Adopt the same service endpoint for fetching spreadsheets as we have for NMNH (we developed a service for NMNH to return pointers to the hashed name of the spreadsheet corresponding to a loaded expedition--- or "project" in arms terms).  I forget if this service is deployed for NMNH, or perhaps its already in commons, in which case, great--- we're good to go.

The purpose of this is to save ALL loaded spreadsheets so we have a history.  I would like also to implement this feature for BiSciCol in general.  So--- we may want to just make this a feature of commons, but since i think we already just implemented for NMNH it may be tricky to push this feature into commons.. in that case, we can just implement this feature as needed in arms, biscicol, nmnh, or other implementations.
John

**Comment by rodney757** [comment]
added in commits 9840808fde8ae103cd788dc0948f62ae6dbc6aac and 0e9e836e800264492e3357eca64b67669a0c25a5
