### ISSUE TITLE
Choosing project on search bar does not filter appropriate deployments

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#13]
When i choose a project on "Search"
http://arms.biocodellc.com/deployments/search
i get ALL the deployments from all projects.... should just show deployments for the selected project.

**Comment by rodney757** [comment]
I'm not sure why this happens to you. I remember it happened a month or 2
ago as well. However I still can't reproduce the problem.

**Comment by rodney757** [comment]
since we rewrote the search page to use angularjs, this should be fixed now
