### ISSUE TITLE
Generate template default setting does not select all the options

### ISSUE THREAD

**Issue by lplaisance** [biocodellc/arms-fims#14]
When I want to generate a default template, the options siteDetails and replicateLabel under location are not checked. Could we have them check by default?
Thank you

**Comment by rodney757** [comment]
The required columns for validation are checked by default. We would need to make these columns required. Let me know if that is what you want

**Comment by lplaisance** [comment]
It seems that all the columns are checked except for those two (even non required columns). For the required columns, it is not possible to uncheck them (see picture). It would make sense to have them all checked.
Thank you,

Laetitia

![screen shot 2016-09-15 at 12 11 41 pm](https://cloud.githubusercontent.com/assets/19540368/18557739/2e98b2d0-7b3e-11e6-96e5-50fe85719414.jpg)

**Comment by rodney757** [comment]
Ah, I wasn't at my computer and was going off of memory. I have fixed this now. Since the config file is cached, you should see the changes within 24 hrs. Let me know if it doesn't show up by tomorrow afternoon
