### ISSUE TITLE
Link to dataset w/ downloadable Excel File broken from Expedition Mgr Page

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#16]
When a user is logged in and they click on:
Expedition Mgr -> ARMS -> Project (Expedition) -> Datasets associated with this expedition
and then choose a dataset by clicking on the identifier, the link brings them back to the ARMS homepage.

What it _should_ do is bring the user to an ARMS page showing the Dataset Metadata and a link to download the file as Excel.

**Comment by jdeck88** [comment]
After discussion with RJ, decided to remove the "Datasets" option in the Expedition manager for ARMS.... we are ONLY concerned with the Expedition Dataset (the most current), which currently forwards to the ARMS Drupal site.  The Datasets are not stored as versions since back-end data is Mysql

**Comment by rodney757** [comment]
fixed in commit e83ae2d9176a4723c1ebcb99b58fc15f59622a25
