### ISSUE TITLE
Upload Projects shows ALL user projects when logged in

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#17]
When a user uploads dataset, it shows a list of ALL expeditions from all users.
It should only show expeditions from the logged in user.  E.g. login w/ plaisancel@si.edu (see john for passwd) there should only be two expeditions.  Instead it shows ALL expeditions.

**Comment by rodney757** [comment]
fixed in commits 5ceae7575be328dfb3d9e91b4ef7b5931c5814e7 and 39d09d4169261426dd1193386b13561cc1fa730e
