### ISSUE TITLE
Private Projects should not be in Drupal

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#19]
If a project is marked as "Not public" It should not appear in Drupal.  Currently, Drupal can see all projects whether they are marked as private or not.

**Comment by rodney757** [comment]
we originally talked about all expeditions (project on drupla) for ARMS being public. We now want to support private expeditions?

**Comment by rodney757** [comment]
fixed in commit 39d09d4169261426dd1193386b13561cc1fa730e
