### ISSUE TITLE
habitat (NOAA deployment zone) list

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#2]
what values do we want in this list?

**Comment by chrispmeyer** [comment]
Do we have macrohabitiat? If macro habitat - that would be those previous terms like coral reef, mangrove, seagrass, sand, basalt, etc
Habitat here then might be a subset of those such as fore reef, lagoon, patch reef, wall, etc for coral reef

**Comment by chrispmeyer** [comment]
Should look at what NOAA has adopted for their delineations and make sure it can reflect those

**Comment by jdeck88** [comment]
Having trouble finding NOAA habitat delineation.   We need help with this....
One promising reference is from Fish and Wildlife:
http://www.fws.gov/wetlands/Documents/Classification-of-Wetlands-and-Deepwater-Habitats-of-the-United-States.pdf

Marine System Subsystems:
  Subtidal = {Rock Bottom, Unconsolidated Bottom, Aquatic Bed, Reef}
  Intertidal = {Aquatic Bed, Reef, Rock Shore, Unconsolidated Shore}

The reference above contains photos and descriptions of habitats.  At any rate, i don't want to get stuck on habitats too much... Chris, if you could get us the some definitive list that would be great.

**Comment by jdeck88** [comment]
I haven't been able to find anything definitive from NOAA--- should we leave Habitat as freetext for now?

**Comment by jdeck88** [comment]
This has been solved.
