### ISSUE TITLE
Drupal Browse Projects

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#20]
The "Choose Project" Dropdown shown in Drupal should sort projects by Country and then PI and list the Country, PI, and Project Title in the list.  This will help users find their project.

**Comment by rodney757** [comment]
fixed in commit 97fc9ac0634c786a4eeee7fccdd2db4912ddf388

**Comment by rodney757** [comment]
actually fixed in commit af6c012013faa02fb104e2a05597e2e2455c4e1a
