### ISSUE TITLE
substrate type list 

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#3]
what values do we put in substrate type?

**Comment by chrispmeyer** [comment]
I think there is also likely a controlled list for this based on ENVO or something - although I cannot seem to find a list of terms there

The most basic categories would be hard vs. soft

If we have macro habitat - that would include terms like coral reef, mangroves, sand, seagrass, rubble, basalt, etc.

**Comment by jdeck88** [comment]
These are the substrate types from the samples in ARMSMetadataMapping
Coral reef
Dead coral reef
Sand
Sand/rock
Rock

These ones are in the list but i reccomend NOT having
10 cm layer of sediment over a granitic substrate
Sandy bottom
Sandy bottom/Reef 
Rock/relic reef
Oyster reef
Reef

**Comment by chrispmeyer** [comment]
I’m inclined to just have hard or soft as substrate type and then map that to habitat/macrohabitat? 
That would accommodate variation on reef building organisms vs sand/mud, etc.
Only question would be rubbly areas that are somewhat in between - loosely consolidated reef rubble, etc., but I would classify that as hard.
-c

On May 10, 2016, at 1:10 PM, John Deck notifications@github.com wrote:

> These are the substrate types from the samples in ARMSMetadataMapping
> Coral reef
> Dead coral reef
> Sand
> Sand/rock
> Rock
> 
> These ones are in the list but i reccomend NOT having
> 10 cm layer of sediment over a granitic substrate
> Sandy bottom
> Sandy bottom/Reef 
> Rock/relic reef
> Oyster reef
> Reef
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub

Dr. Christopher Meyer
Director, Moorea Biocode Project
Research Zoologist & Curator
Dept of Invertebrate Zoology
National Museum of Natural History
Smithsonian Institution
10th & Constitution Ave NW
Washington DC 20560 USA

Email: meyerc@si.edu
Phone: 1-202-633-1752
http://invertebrates.si.edu/staff/meyer.cfm
http://mooreabiocode.org

**Comment by jdeck88** [comment]
ok,

substrateType {hard, soft}
habitat {???}

On Tue, May 10, 2016 at 1:12 PM, chrispmeyer notifications@github.com
wrote:

> I’m inclined to just have hard or soft as substrate type and then map that
> to habitat/macrohabitat?
> That would accommodate variation on reef building organisms vs sand/mud,
> etc.
> Only question would be rubbly areas that are somewhat in between - loosely
> consolidated reef rubble, etc., but I would classify that as hard.
> -c
> 
> On May 10, 2016, at 1:10 PM, John Deck notifications@github.com wrote:
> 
> > These are the substrate types from the samples in ARMSMetadataMapping
> > Coral reef
> > Dead coral reef
> > Sand
> > Sand/rock
> > Rock
> > 
> > These ones are in the list but i reccomend NOT having
> > 10 cm layer of sediment over a granitic substrate
> > Sandy bottom
> > Sandy bottom/Reef
> > Rock/relic reef
> > Oyster reef
> > Reef
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> 
> Dr. Christopher Meyer
> Director, Moorea Biocode Project
> Research Zoologist & Curator
> Dept of Invertebrate Zoology
> National Museum of Natural History
> Smithsonian Institution
> 10th & Constitution Ave NW
> Washington DC 20560 USA
> 
> Email: meyerc@si.edu
> Phone: 1-202-633-1752
> http://invertebrates.si.edu/staff/meyer.cfm
> http://mooreabiocode.org
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/biocodellc/arms-fims/issues/3#issuecomment-218276656

## 

John Deck
(541) 914-4739

**Comment by jdeck88** [comment]
We have this worked out now:

 <list alias="substrateType" caseInsensitive="true">
                <field>hard</field>
                <field>soft</field>
                <field>mixed</field>
            </list>
