### ISSUE TITLE
Some better styling for ARMS homepage-- 

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/arms-fims#5]
develop styling for ARMS FIMS homepage, and this is something that can be mimicked on the Drupal site.  At any rate, something at least to distinguish it from biscicol .

**Comment by rodney757** [comment]
okay, drupal and arms-fims have similar styling now. We need a logo still, and maybe to replace the arms-fims graphic explaining how to validate and upload to help distinguish biscicol and arms-fims.

**Comment by jdeck88** [comment]
This is good for now, marking complete
